# Generated by Django 4.2.16 on 2024-10-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.BinaryField(max_length=100)),
                ('url', models.URLField()),
                ('creation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('student_number', models.IntegerField()),
                ('scolarity', models.FloatField()),
                ('sector', models.TextField(choices=[('Commerce', 'Commerce'), ('Droit', 'Droit'), ('Informatique', 'Informatique')])),
                ('is_eed', models.BooleanField(default=True)),
            ],
        ),
    ]
