# Generated by Django 4.2.16 on 2024-10-10 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='password',
            field=models.BinaryField(max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='scolarity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10000.0)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
