# Generated by Django 4.2.16 on 2024-10-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_school_email_alter_school_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='scolarity',
            new_name='payment',
        ),
    ]
