# Generated by Django 4.2.16 on 2024-10-11 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_scolarity_school_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
    ]
