# Generated by Django 4.2.16 on 2024-10-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_school_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='url',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='payment',
            new_name='tuition_fees',
        ),
    ]
