# Generated by Django 4.2.16 on 2024-10-11 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_url_school_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='password',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
